<?php
/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
 * By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
 * find the sum of the even-valued terms.
 */

// get limit from STD input
fscanf(STDIN, "%d\n", $limit);

if (!intval($limit)) {
	die('Please provide limit');
}

$x = 0;
$y = 1;

$sum = 0;
while (($x + $y) < $limit) {
	
	// sum even value
	if ($y%2 == 0) {
		$sum += $y;
	}
	
	// move to the next Fibonacci number
	$new_x = $y;
	$y = $y + $x;
	$x = $new_x; 
}

fwrite(STDOUT, $sum);